version: '3.8'

services:
  app:
    image: porto
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_ci3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_kampus
    ports:
      - "3306:3306"
